#!/bin/bash
echo " *******************************************************"
echo " *                                                     *"
echo " *                       cmbge                         *"
echo " *                                                     *"
echo " *               Combine 2 GEIA pgm file               *"
echo " *                                                     *"
echo " *                                                     *"
echo " *     Martin Aube 2002                                *"
echo " *                                                     *"
echo " *******************************************************"
echo " "
folder=`pwd`

rm -f core
echo " Experiment directory "$folder
ln -s ~/AODSEM/Bin/cmbgeiapgm cmbgeiapgm
echo " Executing cmbgeiapgm..."

./cmbgeiapgm
echo " Deleting temporary files in " $folder
rm -f cmbgeiapgm

if [ -f core ] 
   then   echo "******** An error occured during execution of cmbge! ********"
   rm -f core
   echo "Hit <CTRL-c> or <CRTL-z> to kill that process"
   read bidon
else
  echo " Normal end of cmbge." 
fi 
