#!/bin/bash
echo "*******************************************************"
echo "*                                                     *"
echo "*             Edit parameter for angstrom             *"
echo "*                                                     *"
echo "*          Aerosol optical depth map spectral         *"
echo "*                     interpolation                   *"
echo "*                                                     *"
echo "*     Martin Aube 2000                                *"
echo "*                                                     *"
echo "*******************************************************"
echo " "
folder=`pwd`
echo " Experiment directory "$folder
echo " "
if [ -f coloraod.par ] 
   then   echo " Actual parameters set to:"
          echo " "
          more angstrom.par
fi 
ls *.pgm
echo " "
echo " New parameters:"
echo " "
echo "root name of the files (.pgm will be added) ?"  
read nom
echo "Source wavelength in nm?"
read wave1
echo "Target wavelength in nm?"
read wave2
echo $nom "   Root name of the files (ext .pgm will be added)"  > angstrom.par
echo $wave1 "   Source wavelength in nm">> angstrom.par
echo $wave2 "   Target wavelength in nm">> angstrom.par
echo "Done"
