#!/bin/bash
echo " *******************************************************"
echo " *                                                     *"
echo " *            Edit parameter for reid2abba             *"
echo " *                                                     *"
echo " *         Convert Jeff Reid ABBA files into           *"
echo " *              Elaine Prins ABBA format               *"
echo " *                                                     *"
echo " *     Martin Aube 2003                                *"
echo " *                                                     *"
echo " *******************************************************"
echo " "
folder=`pwd`
echo " Experiment directory "$folder
echo " "
if [ -f reid2abba.par ] 
   then   echo " Actual parameters set to:"
          echo " "
          more reid2abba.par
fi 

echo " "
echo " New parameters:"
echo " "

echo "Name of the file containing le input Reid file list?"
read inpf
echo "Output file name ?"
read outf

echo $inpf "   Reid file list" > reid2abba.par
echo $outf "   Output file name " >> reid2abba.par

echo "Done"
