#!/bin/bash
echo " *******************************************************"
echo " *                                                     *"
echo " *                       g23ds                         *"
echo " *                                                     *"
echo " *            Convert GEIA file format into            *"
echo " *                   AODSEM 3ds format                 *"
echo " *                                                     *"
echo " *     Martin Aube 2003                                *"
echo " *                                                     *"
echo " *******************************************************"
echo " "
folder=`pwd`

rm -f core
echo " Experiment directory "$folder
ln -s ~/AODSEM/Bin/geia23ds geia2pgm
echo " Executing geia23ds..."

./geia23ds
echo " Deleting temporary files in " $folder
rm -f geia23ds

if [ -f core ] 
   then   echo "******** An error occured during execution of g23ds! ********"
   rm -f core
   echo "Hit <CTRL-c> or <CRTL-z> to kill that process"
   read bidon
else
  echo " Normal end of g23ds." 
fi 
